-- MySQL Script generated by MySQL Workbench
-- Mon Apr  9 14:45:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `state_id` INT NOT NULL,
  `state_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`state_id`));


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_username` VARCHAR(16) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(32) NOT NULL,
  `user_create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_birthday` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `fk_user_state_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `fk_user_state_id`),
  INDEX `fk_user_state_idx` (`fk_user_state_id` ASC),
  CONSTRAINT `fk_user_state`
    FOREIGN KEY (`fk_user_state_id`)
    REFERENCES `mydb`.`State` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`ApartmentOwnership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ApartmentOwnership` (
  `apartment_ownership_id` INT NOT NULL,
  `apartment_ownership_oib` VARCHAR(45) NOT NULL,
  `apartment_ownership_user_id` INT NOT NULL,
  `apartment_ownership_user_state_id` INT NOT NULL,
  PRIMARY KEY (`apartment_ownership_id`),
  INDEX `fk_ApartmentsOwnership_User1_idx` (`apartment_ownership_user_id` ASC, `apartment_ownership_user_state_id` ASC),
  CONSTRAINT `fk_ApartmentsOwnership_User1`
    FOREIGN KEY (`apartment_ownership_user_id` , `apartment_ownership_user_state_id`)
    REFERENCES `mydb`.`User` (`user_id` , `fk_user_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apartment` (
  `apartment_id` INT NOT NULL,
  `apartment_place` VARCHAR(45) NOT NULL,
  `apartment_street` VARCHAR(45) NOT NULL,
  `apartment_ApartmentsOwnership_id` INT NOT NULL,
  `apartment_description` VARCHAR(1024) NULL,
  PRIMARY KEY (`apartment_id`, `apartment_ApartmentsOwnership_id`),
  INDEX `fk_Apartment_ApartmentsOwnership1_idx` (`apartment_ApartmentsOwnership_id` ASC),
  CONSTRAINT `fk_Apartment_ApartmentsOwnership1`
    FOREIGN KEY (`apartment_ApartmentsOwnership_id`)
    REFERENCES `mydb`.`ApartmentOwnership` (`apartment_ownership_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VisitPeriod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VisitPeriod` (
  `visit_period_id` INT NOT NULL,
  `visit_period_date_from` DATETIME NOT NULL,
  `visit_period_date_to` DATETIME NOT NULL,
  PRIMARY KEY (`visit_period_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentDate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentDate` (
  `payment_id` INT NOT NULL,
  `payment_date` DATETIME NOT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `bill_id` INT NOT NULL,
  `bill_amount` INT NOT NULL,
  `bill_payment_date_id` INT NOT NULL,
  PRIMARY KEY (`bill_id`, `bill_payment_date_id`),
  INDEX `fk_Bill_PaymentDate1_idx` (`bill_payment_date_id` ASC),
  CONSTRAINT `fk_Bill_PaymentDate1`
    FOREIGN KEY (`bill_payment_date_id`)
    REFERENCES `mydb`.`PaymentDate` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `room_id` INT NOT NULL,
  `room_size` INT NOT NULL,
  `room_price` INT NOT NULL,
  `room_desctiption` INT NOT NULL,
  `room_Apartment_id` INT NOT NULL,
  `room_Apartment_ApartmentsOwnership_id` INT NOT NULL,
  PRIMARY KEY (`room_id`, `room_Apartment_id`, `room_Apartment_ApartmentsOwnership_id`),
  INDEX `fk_Room_Apartment1_idx` (`room_Apartment_id` ASC, `room_Apartment_ApartmentsOwnership_id` ASC),
  CONSTRAINT `fk_Room_Apartment1`
    FOREIGN KEY (`room_Apartment_id` , `room_Apartment_ApartmentsOwnership_id`)
    REFERENCES `mydb`.`Apartment` (`apartment_id` , `apartment_ApartmentsOwnership_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visit` (
  `visit_id` INT NOT NULL,
  `visit_user_id` INT NOT NULL,
  `visit_user_state_id` INT NOT NULL,
  `visit_visit_period_id` INT NOT NULL,
  `visit_bill_id` INT NOT NULL,
  `visit_room_id` INT NOT NULL,
  `visit_room_apartment_id` INT NOT NULL,
  `visit_room_apartment_ApartmentsOwnership_id` INT NOT NULL,
  PRIMARY KEY (`visit_id`, `visit_user_id`, `visit_user_state_id`, `visit_visit_period_id`, `visit_bill_id`, `visit_room_id`, `visit_room_apartment_id`, `visit_room_apartment_ApartmentsOwnership_id`),
  INDEX `fk_Visit_User1_idx` (`visit_user_id` ASC, `visit_user_state_id` ASC),
  INDEX `fk_Visit_VisitPeriod1_idx` (`visit_visit_period_id` ASC),
  INDEX `fk_Visit_Bill1_idx` (`visit_bill_id` ASC),
  INDEX `fk_Visit_Room1_idx` (`visit_room_id` ASC, `visit_room_apartment_id` ASC, `visit_room_apartment_ApartmentsOwnership_id` ASC),
  CONSTRAINT `fk_Visit_User1`
    FOREIGN KEY (`visit_user_id` , `visit_user_state_id`)
    REFERENCES `mydb`.`User` (`user_id` , `fk_user_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_VisitPeriod1`
    FOREIGN KEY (`visit_visit_period_id`)
    REFERENCES `mydb`.`VisitPeriod` (`visit_period_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Bill1`
    FOREIGN KEY (`visit_bill_id`)
    REFERENCES `mydb`.`Bill` (`bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Room1`
    FOREIGN KEY (`visit_room_id` , `visit_room_apartment_id` , `visit_room_apartment_ApartmentsOwnership_id`)
    REFERENCES `mydb`.`Room` (`room_id` , `room_Apartment_id` , `room_Apartment_ApartmentsOwnership_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
